site_name: Featureform API Reference
theme: "material"
plugins:
- search
- mkdocstrings
- gen-files:
    scripts:
    - gen_pages.py
- literate-nav:
      nav_file: index.md
markdown_extensions:
  - toc:
      permalink: "#"
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences