apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    run: {{ .Release.Name }}-api-server
  name: {{ .Release.Name }}-api-server
spec:
  replicas: 1
  selector:
    matchLabels:
      run: {{ .Release.Name }}-api-server
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: {{ .Release.Name }}-api-server
    spec:
      containers:
        - image: {{ .Values.image.repository }}
          name: {{ .Release.Name }}-api-server
          ports:
            - containerPort: 7878
          resources: {}
          env:
            - name: TYPESENSE_PORT
              value: "80"
            - name: TYPESENSE_HOST
              value: sandbox-typesense
            - name: TYPESENSE_APIKEY
              value: password
            - name: ETCD_HOST
              value: sandbox-etcd
            - name: ETCD_PORT
              value: "2379"
status: {}
