apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    run: sandbox-api-server
  name: sandbox-api-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sandbox-api-server
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: sandbox-api-server
    spec:
      containers:
        - image: {{ .Values.image.repository }}
          name: sandbox-api-server
          ports:
            - containerPort: 7878
              protocol: TCP
          resources: {}
          env:
            - name: API_PORT
              value: "7878"
            - name: METADATA_HOST
              value: "featureform-metadata-server"
            - name: METADATA_PORT
              value: "8080"
            - name: SERVING_HOST
              value: "featureform-feature-server"
            - name: SERVING_PORT
              value: "8080"
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
          livenessProbe:
            httpGet:
              path: /_ah/
              port: 8443
            initialDelaySeconds: 120
            periodSeconds: 3
status: {}
