apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  name: {{ .Release.Name }}-api-server
spec:
  ports:
    - name: grpc
      port: {{ .Values.grpc.port }}
      protocol: TCP
      targetPort: 7878
  selector:
    run: {{ .Release.Name }}-api-server
status:
  loadBalancer: {}

