apiVersion: v1
kind: Service
metadata:
  name: {{ include "redis.fullname" . }}
  labels:
    {{- include "redis.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 5432
      targetPort: 6379
      protocol: TCP
      name: http
  selector:
    {{- include "redis.selectorLabels" . | nindent 4 }}
