apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    run: featureform-feature-server
  name: featureform-feature-server
spec:
  replicas: 1
  selector:
    matchLabels:
      run: featureform-feature-server
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: featureform-feature-server
    spec:
      containers:
        - image: {{ .Values.image.repository }}
          name: featureform-feature-server
          ports:
            - containerPort: {{ .Values.serving.port }}
            - containerPort: {{ .Values.metrics.port }}
          env:
            - name: SERVING_PORT
              value: "0.0.0.0:"{{ .Values.serving.port }}
            - name: METRICS_PORT
              value: "0.0.0.0:"{{ .Values.matrics.port }}
          resources: {}
status: {}
