name: Coverage Testing
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16

      - name: Install grpc_tools
        working-directory: ./ff/serving
        run: pip install grpcio-tools

      - name: Install Protobuf
        working-directory: ./ff/serving
        run: sudo snap install protobuf --classic

      - name: Setup Proto
        working-directory: ./ff/serving
        run: ./gen_grpc.sh

      - name: Build
        working-directory: ./ff/serving
        run: go test -coverprofile cover.out ./...