name: Local Tests
on: [push]

jobs:
  setup:
    name: Setup Test Dependencies
    defaults:
      run:
        working-directory: ./
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Check directory
        run: |
          ls -la

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: Install grpc_tools
        run: pip install grpcio-tools

      - name: Install Protobuf
        run: sudo snap install protobuf --classic

      - name: Setup Proto
        run: ./gen_grpc.sh

      - uses: actions/upload-artifact@v3
        with:
          name: compiled-workdir
          path: ./
          retention-days: 1
  test:
    needs: setup
    runs-on: ${{ matrix.os }}
    strategy:
        matrix:
          os: [ubuntu-latest, macos-latest, osx-arm64, windows-latest]
          python-version: [ '3.7', '3.8', '3.9', '3.10' ]
    steps:
      - name: Download Working Compiled Directories
        uses: actions/download-artifact@v3
        with:
          name: compiled-workdir

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - run: pip install build pytest

      - run: chmod +x ./pip_update.sh
      - run: ./pip_update.sh

      - run: curl https://featureform-demo-files.s3.amazonaws.com/transactions.csv -o transactions.csv

      - run: python -m featureform apply client/examples/local_quickstart.py --local

      - run: pytest client/tests/localmode.py