name: Local Tests
on: [push]

jobs:
  setup:
    runs-on: ubuntu-latest
    strategy:
        matrix:
          python-version: [ '3.7', '3.8', '3.9' ]
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: Install grpc_tools
        run: pip install grpcio-tools

      - name: Install Protobuf
        run: sudo snap install protobuf --classic

      - name: Setup Proto
        run: ./gen_grpc.sh


      - run: pip install build pytest

      - run: ./pip_update.sh

      - run: curl https://featureform-demo-files.s3.amazonaws.com/transactions.csv -o transactions.csv

      - run: featureform apply client/examples/local_quickstart.py --local

      - run: pytest client/tests/localmode.py