name: Testing
on: [push, pull_request]

env:
  TYPESENSE_PORT: 8108
  TYPESENSE_API_KEY: "xyz"
  REDIS_PORT: 6379
  POSTGRES_USER: "username"
  POSTGRES_DB: "default"
  POSTGRES_PASSWORD: "password"


jobs:
  setup:
    name: Setup Test Dependencies
    defaults:
      run:
        working-directory: ./ff/serving
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: Install grpc_tools
        run: pip install grpcio-tools

      - name: Install Protobuf
        run: sudo snap install protobuf --classic

      - name: Setup Proto
        run: ./gen_grpc.sh

      - name: Build
        run: go build

      - uses: actions/upload-artifact@v3
        with:
          name: compiled-workdir
          path: ./ff/serving/
          retention-days: 1

  typesense:
    name: Typesense Testing
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Download Working Compiled Directories
        uses: actions/download-artifact@v3
        with:
          name: compiled-workdir

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      # Installing Typesense manually b/c the base container uses input arguments that
      # Github Actions currently doesn't support (e.g. --data-dir, --api-key, --enable-cores).
      # Can create a custom Typesense container in the future if desired
      - name: Install Typesense Container
        run: docker pull typesense/typesense:0.22.2

      - name: Start Typesense
        run: |
          mkdir /tmp/typesense-data
          docker run -d -p $TYPESENSE_PORT:8108 -v/tmp/typesense-data:/data typesense/typesense:0.22.2 \
          --data-dir /data --api-key=$TYPESENSE_API_KEY --enable-cors

      - name: Make Coverage Directory
        working-directory: ./metadata/search
        run: mkdir coverage

      - name: Testing
        working-directory: ./metadata/search
        continue-on-error: true
        run: go test -v -coverpkg=./... -coverprofile coverage/cover.out ./...

      - name: Convert Coverage Test Results
        working-directory: ./metadata/search/coverage
        run: go tool cover -html=cover.out -o cover.html

      - name: Archive code coverage results
        uses: actions/upload-artifact@v3
        with:
          name: typesense-code-coverage-reports
          path: ./metadata/search/coverage

  provider:
    name: Provider Testing
    needs: setup
    runs-on: ubuntu-latest
    services:
      redis:
        image: redis
        # Hard coded port because environment variables not currently
        # supported for use outside of 'steps'
        ports:
          -  6379:6379

      postgres:
        image: postgres
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: ${{ env.POSTGRES_USER }}
          POSTGRES_DB:  ${{ env.POSTGRES_DB }}
          POSTGRES_PASSWORD: ${{ env.POSTGRES_PASSWORD }}

    steps:
      - name: Download Working Compiled Directories
        uses: actions/download-artifact@v3
        with:
          name: compiled-workdir

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: Testing
        working-directory: ./provider
        continue-on-error: true
        run: go test -v -coverpkg=./... -coverprofile cover.out ./...

      - name: Convert Coverage Test Results
        working-directory: ./provider
        run: go tool cover -html=cover.out -o cover.html

      - name: Archive code coverage results
        uses: actions/upload-artifact@v3
        with:
          name: provider-code-coverage-report
          path: ./provider/cover.html

# TODO
#  etcd:
#    name: ETCD Testing
#    needs: setup
#    runs-on: ubuntu-latest
#    services:
#      redis:
#        image: redis
#        # Hard coded port because environment variables not currently
#        # supported for use outside of 'steps'
#        ports:
#          -  6379:6379
#
#    steps:
#      - name: Download Working Compiled Directories
#        uses: actions/download-artifact@v3
#        with:
#          name: compiled-workdir
#
#      - name: Set up Go
#        uses: actions/setup-go@v2
#        with:
#          go-version: 1.17
#
#      - name: Testing
#        working-directory: ./metadata
#        run: go test -v -coverpkg=./... -coverprofile cover.out ./...
#
#      - name: Convert Coverage Test Results
#        working-directory: ./metadata
#        run: go tool cover -html=cover.out -o cover.html
#
#      - name: Archive code coverage results
#        uses: actions/upload-artifact@v3
#        with:
#          name: etcd-code-coverage-report
#          path: ./metadata/cover.html

  metrics:
    name: Metrics Testing
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Download Working Compiled Directories
        uses: actions/download-artifact@v3
        with:
          name: compiled-workdir

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: Testing
        working-directory: ./metrics
        continue-on-error: true
        run: go test ./... -v -coverpkg=./... -coverprofile cover.out ./...

      - name: Convert Coverage Test Results
        working-directory: ./metrics
        run: go tool cover -html=cover.out -o cover.html

      - name: Archive code coverage results
        uses: actions/upload-artifact@v3
        with:
          name: metrics-code-coverage-report
          path: ./metrics/cover.html

  runner:
    name: Runner Testing
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Download Working Compiled Directories
        uses: actions/download-artifact@v3
        with:
          name: compiled-workdir

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: Testing
        working-directory: ./runner
        continue-on-error: true
        run: go test ./... -v -coverpkg=./... -coverprofile cover.out ./...

      - name: Convert Coverage Test Results
        working-directory: ./runner
        run: go tool cover -html=cover.out -o cover.html

      - name: Archive code coverage results
        uses: actions/upload-artifact@v3
        with:
          name: runner-code-coverage-report
          path: ./runner/cover.html

  coverage:
    name: Upload Coverage
    needs: [typesense, provider, metrics, runner]
    defaults:
      run:
        working-directory: ./
    runs-on: ubuntu-latest
    steps:
      - name: Download Working Compiled Directories
        uses: actions/download-artifact@v3
        with:
          path: ./

      - name: Display structure of downloaded files
        run: ls -R

#      - uses: codecov/codecov-action@v2
#        with:
#          files: ./ff/serving/cover.out
#          name: coverage-upload
#          verbose: true
#
#      - name: Convert Coverage Test Results
#        run: go tool cover -html=cover.out -o cover.html

